-- LAB01-----------------

-- Bài 1: Sinh viên cài đặt hoàn chỉnh bằng các câu lệnh SQL cho 2 CSDL
--QuanLyBanHang (Phần I, câu 1 bài tập thực hành trang 3) và
--QuanLyGiaoVu (Phần I, câu 1 bài tập thực hành trang 11).
CREATE DATABASE QLBH
USE QLBH
CREATE TABLE NHANVIEN
(
	MANV	CHAR(4) PRIMARY KEY,
	HOTEN	VARCHAR(40),
	SODT	VARCHAR(20),
	NGVL	SMALLDATETIME
)
CREATE TABLE KHACHHANG
(
	MAKH	CHAR(4) PRIMARY KEY, 
	HOTEN	VARCHAR(40),
	DCHI	VARCHAR(50),
	SODT	VARCHAR(20),
	NGSINH	SMALLDATETIME,
	NGDK	SMALLDATETIME,
	DOANHSO	MONEY
)
CREATE TABLE SANPHAM
(
	MASP	CHAR(4) PRIMARY KEY,
	TENSP	VARCHAR(40),
	DVT		VARCHAR(20),
	NUOCSX	VARCHAR(40),
	GIA		MONEY
)
CREATE TABLE HOADON(
	SOHD	INT PRIMARY KEY,
	NGHD	SMALLDATETIME,
	MAKH	CHAR(4) REFERENCES KHACHHANG(MAKH),
	MANV	CHAR(4) REFERENCES NHANVIEN(MANV),
	TRIGIA	MONEY
)
CREATE TABLE CTHD
(	
	SOHD	INT REFERENCES HOADON(SOHD),
	MASP	CHAR(4) REFERENCES SANPHAM(MASP),
	SL		INT
	PRIMARY KEY(SOHD, MASP)
)

CREATE DATABASE QLGV
USE QLGV

CREATE TABLE KHOA 
(
	MAKHOA	VARCHAR(4) PRIMARY KEY,
	TENKHOA	VARCHAR(40),
	NGTLAP	SMALLDATETIME,
	TRGKHOA	CHAR(4)
)
CREATE TABLE MONHOC
(	
	MAMH	VARCHAR(10) PRIMARY KEY,
	TENMH	VARCHAR(40),
	TCLT	TINYINT,
	TCTH	TINYINT,
	MAKHOA	VARCHAR(4) REFERENCES KHOA(MAKHOA)
)
CREATE TABLE DIEUKIEN
(	
	MAMH VARCHAR(10) REFERENCES MONHOC(MAMH),
	MAMH_TRUOC	VARCHAR(10)
	PRIMARY KEY (MAMH, MAMH_TRUOC)
)
CREATE TABLE GIAOVIEN
(
	MAGV	CHAR(4) PRIMARY KEY,
	HOTEN	VARCHAR(40),
	HOCVI	VARCHAR(10),
	HOCHAM	VARCHAR(10),
	GIOITINH	VARCHAR(3),
	NGSINH	SMALLDATETIME,
	NGVL	SMALLDATETIME,
	HESO	NUMERIC(4,2),
	MUCLUONG	MONEY,
	MAKHOA	VARCHAR(4) REFERENCES KHOA(MAKHOA)
)
CREATE TABLE LOP
(
	MALOP	CHAR(3) PRIMARY KEY,
	TENLOP	VARCHAR(40),
	TRGLOP	CHAR(5),
	SISO	TINYINT,
	MAGVCN	CHAR(4) REFERENCES GIAOVIEN(MAGV)
)
CREATE TABLE HOCVIEN
(
	MAHV	CHAR(5) PRIMARY KEY,
	HO		VARCHAR(40),
	TEN		VARCHAR(10),
	NGSINH	SMALLDATETIME,
	GIOITINH	VARCHAR(3),
	NOISINH		VARCHAR(40),
	MALOP	CHAR(3) REFERENCES LOP(MALOP)
)
CREATE TABLE GIANGDAY
(
	MALOP	CHAR(3) REFERENCES LOP(MALOP),
	MAMH	VARCHAR(10) REFERENCES MONHOC(MAMH),
	MAGV	CHAR(4)	REFERENCES GIAOVIEN(MAGV),
	HOCKY	TINYINT,
	NAM		SMALLINT,
	TUNGAY	SMALLDATETIME,
	DENNGAY	SMALLDATETIME,
	PRIMARY KEY (MALOP, MAMH)
)
CREATE TABLE KETQUATHI
(
	MAHV	CHAR(5) REFERENCES HOCVIEN(MAHV),
	MAMH	VARCHAR(10) REFERENCES MONHOC(MAMH),
	LANTHI	TINYINT,
	NGTHI	SMALLDATETIME,
	DIEM	NUMERIC(4,2),
	KQUA	VARCHAR(10),
	PRIMARY KEY (MAHV, MAMH, LANTHI)
)
ALTER TABLE KHOA ADD CONSTRAINT FK_KHOA_TRGKHOA FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV)
ALTER TABLE LOP ADD CONSTRAINT FK_LOP_TRGLOP FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV)
ALTER TABLE HOCVIEN
ADD GHICHU varchar(50)
ALTER TABLE HOCVIEN
ADD DIEMTB numeric(4,2)
ALTER TABLE HOCVIEN
ADD XEPLOAI varchar(10)


-- Bài 2: Sinh viên hoàn thành Phần I bài tập QuanLyBanHang từ câu 2 đến câu 10.
-- 2. Thêm vào thuộc tính GHICHU có kiểu dữ liệu varchar(20) cho quan hệ SANPHAM.
ALTER TABLE SANPHAM ADD GHICHU VARCHAR(20)
-- 3. Thêm vào thuộc tính LOAIKH có kiểu dữ liệu là tinyint cho quan hệ KHACHHANG
ALTER TABLE KHACHHANG ADD LOAIKH TINYINT
-- 4. Sửa kiểu dữ liệu của thuộc tính GHICHU trong quan hệ SANPHAM thành varchar(100).
ALTER TABLE SANPHAM ALTER COLUMN GHICHU VARCHAR(100)
-- 5. Xóa thuộc tính GHICHU trong quan hệ SANPHAM.
ALTER TABLE SANPHAM DROP COLUMN GHICHU
-- 6.Làm thế nào để thuộc tính LOAIKH trong quan hệ KHACHHANG có thể lưu các giá trị là: “Vang lai”, “Thuong xuyen”, “Vip”…
ALTER TABLE KHACHHANG ADD CONSTRAINT CK_LKH CHECK (LOAIKH IN ('Van lai', 'Thuong xuyen', 'Vip'))
-- 7.Đơn vị tính của sản phẩm chỉ có thể là (“cay”,”hop”,”cai”,”quyen”,”chuc”)
ALTER TABLE SANPHAM ADD CONSTRAINT CK_DVT CHECK (DVT IN ('cay', 'hop','cai','quyen','chuc'))
-- 8.Giá bán của sản phẩm từ 500 đồng trở lên.
ALTER TABLE SANPHAM ADD CONSTRAINT CK_GIA CHECK (GIA >= 500)
-- 9.Mỗi lần mua hàng, khách hàng phải mua ít nhất 1 sản phẩm.
ALTER TABLE CTHD ADD CONSTRAINT CK_SL CHECK (SL >= 1)
-- 10.Ngày khách hàng đăng ký là khách hàng thành viên phải lớn hơn ngày sinh của người đó.
ALTER TABLE KHACHHANG ADD CONSTRAINT CK_NGDK CHECK (NGDK > NGSINH)

-- Bài 3: Sinh viên hoàn thành Phần I bài tập QuanLyGiaoVu từ câu 3 đến câu 8.
-- 3.Thuộc tính GIOITINH chỉ có giá trị là “Nam” hoặc “Nu”.
ALTER TABLE HOCVIEN
ADD CONSTRAINT CK_GIOITINH_HV CHECK(GIOITINH IN ('Nam', 'Nu'))
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CK_GIOITINH_GV CHECK(GIOITINH IN ('Nam', 'Nu'))
-- 4.	Điểm số của một lần thi có giá trị từ 0 đến 10 và cần lưu đến 2 số lẽ (VD: 6.22).
ALTER TABLE KETQUATHI ADD CONSTRAINT CK_DIEM
CHECK (
	DIEM BETWEEN 0 AND 10
	AND DIEM = ROUND(DIEM, 2)
)
-- 5.Kết quả thi là “Dat” nếu điểm từ 5 đến 10  và “Khong dat” nếu điểm nhỏ hơn 5.
ALTER TABLE KETQUATHI ADD CONSTRAINT CK_KQUA
CHECK (KQUA = IIF(DIEM < 5, 'Khong dat', 'Dat'))
-- 6.	Học viên thi một môn tối đa 3 lần
ALTER TABLE KETQUATHI ADD CONSTRAINT CK_LT CHECK (LANTHI <= 3)
-- 7. Học kỳ chỉ có giá trị từ 1 đến 3
ALTER TABLE GIANGDAY ADD CONSTRAINT CK_HK CHECK (HOCKY BETWEEN 1 AND 3)
-- 8. Học vị của giáo viên chỉ có thể là “CN”, “KS”, “Ths”, ”TS”, ”PTS”
ALTER TABLE GIAOVIEN ADD CONSTRAINT CK_HV CHECK (HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'))
